title: Benvido a Formaweb IV
author: sformaweb
email: email@email.com
description: > # this means to ignore newlines until "baseurl:"
  Este Ã© o blog de Formaweb IV, un programa de emprego do Concello de Vigo.

# social links
twitter_username: abelcaballero # DO NOT include the @ character, or else the build will fail!
github_username:  sformaweb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

